### ISSUE TITLE
Getting an UserWarning while running django server 

### ISSUE THREAD

**Issue by devarshigoswami** [vladislavalerievich/portfolio-website#1]
I cloned the repo, Installed whitenoise and tried dev server using `python manage.py runserver` but I get the error
```
anaconda3/lib/python3.7/site-packages/whitenoise/base.py:116: UserWarning: No directory at: /DEV/portfolio/Django-personal-website/portfolio/staticfiles/
  warnings.warn(u"No directory at: {}".format(root))
```
 The server runs although, but it looks like this.
                     
![Screenshot at 2020-03-13 15-10-57](https://user-images.githubusercontent.com/55073596/76609450-6cbda600-653d-11ea-9965-9fd2a481c46c.png)

What might be the core issue and how do I tackle it?

**Comment by philippmaph** [comment]
I reckon you double check the root repo as in the structure of the whole project as there seems to be some sort of misplacement between your directory.

**Comment by motasim123** [comment]
> I cloned the repo, Installed whitenoise and tried dev server using `python manage.py runserver` but I get the error
> 
> ```
> anaconda3/lib/python3.7/site-packages/whitenoise/base.py:116: UserWarning: No directory at: /DEV/portfolio/Django-personal-website/portfolio/staticfiles/
>   warnings.warn(u"No directory at: {}".format(root))
> ```
> 
> The server runs although, but it looks like this.
> 
> ![Screenshot at 2020-03-13 15-10-57](https://user-images.githubusercontent.com/55073596/76609450-6cbda600-653d-11ea-9965-9fd2a481c46c.png)
> 
> What might be the core issue and how do I tackle it?

update the path of css file then run the migration after run the server

**Comment by Salinatorimperator** [comment]
hey man, did you manage to fix it? Having the same problem here

**Comment by devarshigoswami** [comment]
nope , built my portfolio with gatsby.js instead :P

**Comment by Salinatorimperator** [comment]
OK.
In case you want to know the problem was it couldn't load the js files.

For a quick solution change DEBUG to True in `settings.py` (don't do this if you are going to use in Production mode).

For more information: https://docs.djangoproject.com/en/1.8/howto/static-files/

**Comment by sameergaikwad222** [comment]
I have reconfigured Static & templates Directory Settings in My Fork and resolved issue. Please check Settings in my fork clone Pull Request.

I kept Static and Template directory inside folder where manage.py file is located that is outside an app
also added same config.

**BASE_DIR = Path(__file__).resolve().parent.parent**

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': **[os.path.join(BASE_DIR, 'templates')],**
...

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] 


#2
